#!/usr/bin/env bash

set -e 
set -u

# This script will install the ELK stack, Java 8 and Nginx

# Importing Elasticsearch public GPG key into APT
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

# Adding Elastic source list to the sources.list.d dir
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

# Update apt
sudo apt update

# Install elasticsearch
sudo apt install elasticsearch


